### ISSUE TITLE
Toggle to allow removal of transparent backdrop for MathJAX editor

### ISSUE THREAD

**Issue by JosephGarrone** [RoboticsDesignLab/OpenPlatypus#3]
This will allow users to more easily view their current working. Note: The dialog is already draggable.

**Comment by spns** [comment]
By "MathJax editor" I presume this is the CKEdit equation editor -- at which point this is a feature request for the CKEdit community.  

To implement this would mean our own equation editor from scratch.  That's not a minor development effort.

**Comment by JosephGarrone** [comment]
This could easily be overwritten via:

```
.cke_dialog_background_cover {
    opacity: 0 !important;
}
```
